### ISSUE TITLE
Comments on src/static/presentations/github.pdf

### ISSUE THREAD

**Issue by florisvdh** [inbo/git-course#21]
I assumed there is no textual source for `src/static/presentations/github.pdf`, so here are some suggestions:

- content:
  - slide 9: the weblink now redirects to https://github.com/collections which has different content. Not sure whether that still fits the goal.
  - slide 61 and later: note that the schemes assume local vs. remote repos: I assume that in the upcoming workshop also the local branching part will be done in GitHub.
  - slide 62: "he _integrates_ these changes" -> it already happened in the scheme
  - slide 63: "This _was_ done ..." (same reason)
  - slide 91: better enlist "merge" here instead of rebase (switch with footnote)
- typo:
  - slide 6: commits _tell_

For workshop preparation directed at GitHub solely, some introduction (from git.pdf?) may be needed to familiarize with basic concepts of a repository, version control, committing, branching and merging: the presentation more or less assumes this familiarity. If participants need git installed too, that will need to be arranged (though I assume it is not your intention @peterdesmet ).

**Comment by peterdesmet** [comment]
Thanks @florisvdh:

- Slide 9: still fine
- Slide 61: yes
- Slide 62: figure adapted
- Slide 63: left the same
- Slide 91: ok

I have discussed the workshop content with Nico and we will give the `git.pdf` slideshow as an introduction, before doing a hands on.
