### ISSUE TITLE
replace master by main

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/git-course#44]
As the default branch name is nowadays `main` instead of `master`, it seems a good idea to me to replace `master` by `main` throughout this package.  Is there any objection to the fact that I make a PR to change this in the scripts if I find some time for it, @peterdesmet @damianooldoni ?  I don't know how to deal with this for the `.pdf` presentations, do you have any suggestions for it, or can I just leave them as is?

**Comment by peterdesmet** [comment]
No objections, I can try and see if I can find the original presentations, but I will only do that once the PR is there.
